# 1 "/home/priv-gerben/project/gazelle/c11/tests/gcc-src/gcc/testsuite/gcc.c-torture/execute/pr110666-1.c"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 389 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "/home/priv-gerben/project/gazelle/c11/tests/gcc-src/gcc/testsuite/gcc.c-torture/execute/pr110666-1.c" 2
# 32 "/home/priv-gerben/project/gazelle/c11/tests/gcc-src/gcc/testsuite/gcc.c-torture/execute/pr110666-1.c"
int eqeq_0 (int) __attribute__((noipa)); int eqeq_0 (int a) { return (a == 0) == a; } int eqeq_0_v (int) __attribute__((noipa)); int eqeq_0_v (volatile int a) { return (a == 0) == a; } int eqeq_1 (int) __attribute__((noipa)); int eqeq_1 (int a) { return (a == 1) == a; } int eqeq_1_v (int) __attribute__((noipa)); int eqeq_1_v (volatile int a) { return (a == 1) == a; } int eqeq_2 (int) __attribute__((noipa)); int eqeq_2 (int a) { return (a == 2) == a; } int eqeq_2_v (int) __attribute__((noipa)); int eqeq_2_v (volatile int a) { return (a == 2) == a; } int eqne_0 (int) __attribute__((noipa)); int eqne_0 (int a) { return (a != 0) == a; } int eqne_0_v (int) __attribute__((noipa)); int eqne_0_v (volatile int a) { return (a != 0) == a; } int eqne_1 (int) __attribute__((noipa)); int eqne_1 (int a) { return (a != 1) == a; } int eqne_1_v (int) __attribute__((noipa)); int eqne_1_v (volatile int a) { return (a != 1) == a; } int eqne_2 (int) __attribute__((noipa)); int eqne_2 (int a) { return (a != 2) == a; } int eqne_2_v (int) __attribute__((noipa)); int eqne_2_v (volatile int a) { return (a != 2) == a; } int neeq_0 (int) __attribute__((noipa)); int neeq_0 (int a) { return (a == 0) != a; } int neeq_0_v (int) __attribute__((noipa)); int neeq_0_v (volatile int a) { return (a == 0) != a; } int neeq_1 (int) __attribute__((noipa)); int neeq_1 (int a) { return (a == 1) != a; } int neeq_1_v (int) __attribute__((noipa)); int neeq_1_v (volatile int a) { return (a == 1) != a; } int neeq_2 (int) __attribute__((noipa)); int neeq_2 (int a) { return (a == 2) != a; } int neeq_2_v (int) __attribute__((noipa)); int neeq_2_v (volatile int a) { return (a == 2) != a; } int nene_0 (int) __attribute__((noipa)); int nene_0 (int a) { return (a != 0) != a; } int nene_0_v (int) __attribute__((noipa)); int nene_0_v (volatile int a) { return (a != 0) != a; } int nene_1 (int) __attribute__((noipa)); int nene_1 (int a) { return (a != 1) != a; } int nene_1_v (int) __attribute__((noipa)); int nene_1_v (volatile int a) { return (a != 1) != a; } int nene_2 (int) __attribute__((noipa)); int nene_2 (int a) { return (a != 2) != a; } int nene_2_v (int) __attribute__((noipa)); int nene_2_v (volatile int a) { return (a != 2) != a; }
# 46 "/home/priv-gerben/project/gazelle/c11/tests/gcc-src/gcc/testsuite/gcc.c-torture/execute/pr110666-1.c"
int main()
{
  for(int n = -1; n <= 2; n++) {
    if (eqeq_0_v(n) != eqeq_0(n)) __builtin_abort(); if (eqeq_1_v(n) != eqeq_1(n)) __builtin_abort(); if (eqeq_2_v(n) != eqeq_2(n)) __builtin_abort(); if (eqne_0_v(n) != eqne_0(n)) __builtin_abort(); if (eqne_1_v(n) != eqne_1(n)) __builtin_abort(); if (eqne_2_v(n) != eqne_2(n)) __builtin_abort(); if (neeq_0_v(n) != neeq_0(n)) __builtin_abort(); if (neeq_1_v(n) != neeq_1(n)) __builtin_abort(); if (neeq_2_v(n) != neeq_2(n)) __builtin_abort(); if (nene_0_v(n) != nene_0(n)) __builtin_abort(); if (nene_1_v(n) != nene_1(n)) __builtin_abort(); if (nene_2_v(n) != nene_2(n)) __builtin_abort();
  }
}
